---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
---
apiVersion: batch/v1
kind: Job
metadata:
  name: boids0-job
spec:
  template:
    metadata:
      labels:
        app: boids0
    spec:
      restartPolicy: Never
      containers:
      - name: boids0
        image: mjpritch/boids:latest
        imagePullPolicy: Always
        env:
          - name: NPROCS
            value: "3"
          - name: RANK
            value: "0"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
        command: ["/app/wait-for-rabbitmq.sh", "rabbitmq", "5672", "./build/distributed_main", "0", "3"]
        volumeMounts:
          - name: boids-output
            mountPath: /app/output
      volumes:
        - name: boids-output
          hostPath:
            path: /mnt/c/Users/MorganP/BoidsDocker3/RancherOutput/boids0-output
            type: DirectoryOrCreate
---
apiVersion: batch/v1
kind: Job
metadata:
  name: boids1-job
spec:
  template:
    metadata:
      labels:
        app: boids1
    spec:
      restartPolicy: Never
      containers:
      - name: boids1
        image: mjpritch/boids:latest
        imagePullPolicy: Always
        env:
          - name: NPROCS
            value: "3"
          - name: RANK
            value: "1"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
        command: ["/app/wait-for-rabbitmq.sh", "rabbitmq", "5672", "./build/distributed_main", "1", "3"]
        volumeMounts:
          - name: boids-output
            mountPath: /app/output
      volumes:
        - name: boids-output
          hostPath:
            path: /mnt/c/Users/MorganP/BoidsDocker3/RancherOutput/boids1-output
            type: DirectoryOrCreate
---
apiVersion: batch/v1
kind: Job
metadata:
  name: boids2-job
spec:
  template:
    metadata:
      labels:
        app: boids2
    spec:
      restartPolicy: Never
      containers:
      - name: boids2
        image: mjpritch/boids:latest
        imagePullPolicy: Always
        env:
          - name: NPROCS
            value: "3"
          - name: RANK
            value: "2"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
        command: ["/app/wait-for-rabbitmq.sh", "rabbitmq", "5672", "./build/distributed_main", "2", "3"]
        volumeMounts:
          - name: boids-output
            mountPath: /app/output
      volumes:
        - name: boids-output
          hostPath:
            path: /mnt/c/Users/MorganP/BoidsDocker3/RancherOutput/boids2-output
            type: DirectoryOrCreate